# Generated by Django 4.1.2 on 2022-11-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
