# Generated by Django 4.1.2 on 2022-11-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_verification_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='email',
        ),
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
