# Generated by Django 4.1.2 on 2022-11-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_verification_email_verification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
