# Generated by Django 4.1.2 on 2022-11-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('main_topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.maintopic')),
            ],
        ),
    ]
