# Generated by Django 4.1.2 on 2022-11-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_verification'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='main_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.maintopic'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20000)),
                ('author', models.ForeignKey(default='DELETED', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.profile')),
                ('reply', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.comment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic')),
            ],
        ),
    ]
