# Generated by Django 4.1.2 on 2022-11-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='status',
            new_name='Closed',
        ),
    ]
