# Generated by Django 4.1.2 on 2022-11-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_status_topic_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.TextField(default='Topic body', max_length=2000),
        ),
    ]
