# Generated by Django 4.1.2 on 2022-11-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
