# Generated by Django 4.1.2 on 2022-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_topic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
